# config.go > struct 과 항상 일치해야 한다. !!!

server-type = "dev"

[database]
driver-name = "mysql"
url = "10.10.30.10:3306"
database = "ipsap"
username = "root"
password = "tmvmfls!00"
init-version = "1.0.0"

[server]
swag-hostname = "www.ipsap.co.kr"
port = 7375
log-path = "/root/api/batch_log/" #로그 패스가 있을경우, 해당 위치에 로그를 남긴다.
max-backups = 30
working-path = "/root/go/working/"      # 작업 폴더 지정
file-upload-path = ""
protocol = "https"
api-path = "/api/v1.0"
cert = "/app/ipsap_cert/www.ipsap.co.kr_pem.pem"
key = "/app/ipsap_cert/www.ipsap.co.kr_pem.key"

[email]
template-path = "/app/html/html/admin/mail/"
logo-file = "/app/html/assets/images/common/IPSAP_logo_top_fitted.png"

[program]
init-password = "test1234"
encryption-key = "343b684bf08f4e13868680b4b56a88d7" # length : 32

[s3]
bucket_real = "ipsapupload"
bucket_test = "sprintectest"

[payment]
general-mid = "ipsap0120m"  # 알반결제용 MID
general-merchant-key = "BjM/8CMkuQu1qmglz267bmRrQRVCP8NNGEYsKrV5ggLle7KGq/H6SI6D2r2zaKqr6l3RGu3oVCKWD2eQ4ZEEgg==" # 일반결제용 MKEY
regular-mid = "ipsap0121m"  # 정기결제용 MID
regular-merchant-key = "KA8T5jfxznZgoOFZzahd/KCn8lPsiMKoFvyOjCEoIAts4tmpKmWYLU1m2vdZv9I8WXUxjifyToxbkDeGI/kyZQ==" # 정기결제용 MKEY

[test]
is-test-mode = false
is-query-debug = false
