# sms_config.go > struct 과 항상 일치해야 한다. !!!

server-type = "dev"

[database]
driver-name = "mysql"
url = "localhost:3306"
database = "ipsap"
username = "root"
password = "tmvmfls!00"
init-version = "1.0.0"

[sms]
usercode    = "ipsap88"
deptcode    = "1B-4O8-V2"
from        = "025254682"
send-url    = "https://rest.surem.com/{type}/v1/json" # 전송 url sms, lms 경로설정
result-url  = "https://rest.surem.com/recv/{type}"    # 결과 url sms, mms 경로설정

[server]
log-path = "/root/sms/log/" #로그 패스가 있을경우, 해당 위치에 로그를 남긴다.
max-backups = 30
